# Generated by Django 2.0.4 on 2018-04-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_aedes', models.BooleanField(default=False)),
            ],
        ),
    ]
